name: 'Update toolbox.json'

on:
  push:
    branches:
    - autoupdate_toolbox_json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Update toolbox.json
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email "action@github.com"

        sh install

        toolbox update-shell

        if [ `git status --porcelain=v2 | wc -l` -ne 0 ]; then
          echo "Updating toolbox.json file ..."
          git add toolbox.json
          git commit -m "[skip ci] update toolbox.json" -q
          git push -q
        fi
